"""
pythoneda/sandbox/dep/artifact/application/python_dep_application.py

This file defines the PythonDepApplication class.

Copyright (C) 2023-today rydnr's pythoneda-sandbox-artifact/python-dep

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
"""
import asyncio
from pythoneda.shared.artifact import LocalArtifact
from pythoneda.shared.artifact.application import LocalArtifactApp
from pythoneda.sandbox.dep.artifact.infrastructure import LocalPythonDep


class PythonDepApplication(LocalArtifactApp):
    """
    Runs the PythonDepApplication PythonEDA app.

    Class name: PythonDepApplication

    Responsibilities:
        - Runs PythonEDA to launch PythonDep artifact.

    Collaborators:
        - Command-line handlers from pythoneda-shared-artifact/infrastructure
    """

    def __init__(self):
        """
        Creates a new PythonDepApplication instance.
        """
        # python_dep_banner is automatically generated by pythoneda-sandbox/python-dep-artifact-artifact
        banner = None
        try:
            from pythoneda.sandbox.dep.artifact.application.python_dep_banner import (
                PythonDepBanner,
            )

            banner = PythonDepBanner()
        except ImportError:
            pass
        super().__init__(banner, __file__)

    @classmethod
    def local_artifact_class(cls) -> type[LocalArtifact]:
        """
        Retrieves the subclass of LocalArtifact.
        :return: Such class.
        :rtype: type[pythoneda.shared.artifact.LocalArtifact]
        """
        return LocalPythonDep


if __name__ == "__main__":
    asyncio.run(
        PythonDepApplication.main(
            "pythoneda.sandbox.dep.artifact.application.PythonDepApplication"
        )
    )
